# Generated by Django 5.2.1 on 2025-05-11 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_part', '0002_comment_alter_onepart_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='one_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='one_part.onepart'),
            preserve_default=False,
        ),
    ]
