# Generated by Django 5.2.1 on 2025-05-12 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_part', '0004_onepartsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onepart',
            name='video',
            field=models.FileField(upload_to='one_part/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv'])]),
        ),
    ]
